DROP EVENT IF EXISTS UPDATE_YEARS_EVENT;
CREATE EVENT UPDATE_YEARS_EVENT
ON SCHEDULE
    EVERY '1' YEAR
    STARTS '2022-01-01 00:00:00'
DO
BEGIN
    INSERT INTO Years (AdeptusMechanicus_5.Years.year)
    VALUES (YEAR(curdate()));
END;

