INSERT INTO Fuels (fuel, price)
VALUES ('Petrol', 1.45),
       ('Diesel', 1.5),
       ('LPG', 0.65),
       ('CNG', 0.8);

INSERT INTO Jobs (job, salary)
VALUES ('CEO/Managing Director', 25000),
       ('Chief Technology Officer (CTO)', 18000),
       ('Software Development Manager', 17000),
       ('Project Manager', 16000),
       ('Software Architect', 15000),
       ('Network Engineer', 14000),
       ('Data Analyst', 13000),
       ('IT Consultant', 12000),
       ('Database Administrator', 11000),
       ('Security Engineer', 12500),
       ('Development Team Lead', 9000),
       ('Project Lead', 8000),
       ('Production Engineer', 7000),
       ('Resource Manager', 4000),
       ('UX Designer', 8500);

INSERT INTO MobilePlans (plan, price)
VALUES ('30', 15),
       ('60', 20),
       ('90', 25),
       ('120', 30),
       ('Unlimited', 35);

INSERT INTO Months (inMonth)
VALUES ('January'),
       ('February'),
       ('March'),
       ('April'),
       ('May'),
       ('June'),
       ('July'),
       ('August'),
       ('September'),
       ('October'),
       ('November'),
       ('December');

INSERT INTO Cars (car, consumption)
VALUES ('Audi', 7.5),
       ('BMW', 7.8),
       ('Chevrolet', 9.3),
       ('Dodge', 12.5),
       ('Ford', 8.6),
       ('Honda', 6.9),
       ('Hyundai', 7.2),
       ('Jeep', 12.8),
       ('Kia', 7.4),
       ('Lexus', 8.2),
       ('Mazda', 7.6),
       ('Mercedes-Benz', 8.1),
       ('Nissan', 7.8),
       ('Porsche', 11.5),
       ('Subaru', 8.2),
       ('Sufurky', 3.1),
       ('Toyota', 7.2),
       ('Volkswagen', 7.1),
       ('Volvo', 7.5),
       ('Peugeot', 6.8);

INSERT INTO Employees (fname, lname, age, email)
VALUES ('Branislav', 'Valacsay', 40, 'branislav.v@outlook.com'),
       ('Marian', 'Bodnar', 18, 'm_bodnar@gmail.com'),
       ('Milos', 'Vydareny', 41, 'milos.vydareny@paneurouni.com'),
       ('Nikita', 'Tomanec', 21, 'nikita_22@gmail.com'),
       ('Michal', 'Micuch', 30, 'michal_micuch@paneurouni.com'),
       ('Sarah', 'Miller', 28, 'sarah.miller@example.com'),
       ('Ryan', 'Johnson', 42, 'ryan.johnson@example.com'),
       ('Emma', 'Smith', 33, 'emma.smith@example.com'),
       ('John', 'Lee', 56, 'john.lee@example.com'),
       ('Maria', 'Garcia', 23, 'maria.garcia@example.com'),
       ('David', 'Jones', 39, 'david.jones@example.com'),
       ('Samantha', 'Wilson', 46, 'samantha.wilson@example.com'),
       ('Michael', 'Brown', 25, 'michael.brown@example.com'),
       ('Julia', 'Davis', 37, 'julia.davis@example.com'),
       ('Mark', 'Taylor', 49, 'mark.taylor@example.com'),
       ('Melissa', 'Clark', 31, 'melissa.clark@example.com'),
       ('Kevin', 'Thomas', 29, 'kevin.thomas@example.com'),
       ('Rachel', 'Hernandez', 44, 'rachel.hernandez@example.com'),
       ('Steven', 'Gonzalez', 52, 'steven.gonzalez@example.com'),
       ('Emily', 'Wilson', 27, 'emily.wilson@example.com'),
       ('Christopher', 'Jackson', 36, 'christopher.jackson@example.com'),
       ('Sophia', 'Garcia', 21, 'sophia.garcia@example.com'),
       ('Nicholas', 'Anderson', 48, 'nicholas.anderson@example.com'),
       ('Jessica', 'Moore', 40, 'jessica.moore@example.com'),
       ('Daniel', 'Martinez', 34, 'daniel.martinez@example.com'),
       ('Madison', 'Davis', 22, 'madison.davis@example.com'),
       ('Matthew', 'Brown', 41, 'matthew.brown@example.com'),
       ('Olivia', 'Smith', 38, 'olivia.smith@example.com'),
       ('Andrew', 'Johnson', 30, 'andrew.johnson@example.com'),
       ('Isabella', 'Lee', 43, 'isabella.lee@example.com'),
       ('William', 'Wilson', 57, 'william.wilson@example.com'),
       ('Victoria', 'Taylor', 26, 'victoria.taylor@example.com'),
       ('Anthony', 'Garcia', 35, 'anthony.garcia@example.com'),
       ('Grace', 'Clark', 50, 'grace.clark@example.com'),
       ('Christopher', 'Harris', 32, 'christopher.harris@example.com'),
       ('Alexis', 'Anderson', 24, 'alexis.anderson@example.com'),
       ('Joseph', 'Martinez', 47, 'joseph.martinez@example.com'),
       ('Natalie', 'Taylor', 39, 'natalie.taylor@example.com'),
       ('Jason', 'Brown', 31, 'jason.brown@example.com'),
       ('Ava', 'Johnson', 56, 'ava.johnson@example.com'),
       ('Jacob', 'Smith', 29, 'jacob.smith@example.com'),
       ('Mia', 'Lee', 41, 'mia.lee@example.com'),
       ('Amanda', 'Robinson', 27, 'amandarobinson@example.com'),
       ('William', 'Clark', 31, 'williamclark@example.com'),
       ('Stephanie', 'Allen', 25, 'stephanieallen@example.com'),
       ('Christopher', 'Hall', 30, 'christopherhall@example.com'),
       ('Julia', 'Wright', 24, 'juliawright@example.com'),
       ('Joshua', 'Young', 29, 'joshuayoung@example.com'),
       ('Katie', 'Scott', 26, 'katiescott@example.com'),
       ('Brandon', 'Baker', 35, 'brandonbaker@example.com'),
       ('Alexandra', 'Lee', 31, 'alexandralee@example.com'),
       ('Jacob', 'Garcia', 28, 'jacobgarcia@example.com');

INSERT INTO Cars_Fuels (cars_id, fuels_id)
VALUES (1, FLOOR(RAND() * 4) + 1),
       (2, FLOOR(RAND() * 4) + 1),
       (3, FLOOR(RAND() * 4) + 1),
       (4, FLOOR(RAND() * 4) + 1),
       (5, FLOOR(RAND() * 4) + 1),
       (6, FLOOR(RAND() * 4) + 1),
       (7, FLOOR(RAND() * 4) + 1),
       (8, FLOOR(RAND() * 4) + 1),
       (9, FLOOR(RAND() * 4) + 1),
       (10, FLOOR(RAND() * 4) + 1),
       (11, FLOOR(RAND() * 4) + 1),
       (12, FLOOR(RAND() * 4) + 1),
       (13, FLOOR(RAND() * 4) + 1),
       (14, FLOOR(RAND() * 4) + 1),
       (15, FLOOR(RAND() * 4) + 1),
       (16, FLOOR(RAND() * 4) + 1),
       (17, FLOOR(RAND() * 4) + 1),
       (18, FLOOR(RAND() * 4) + 1),
       (19, FLOOR(RAND() * 4) + 1),
       (20, FLOOR(RAND() * 4) + 1);

INSERT INTO Employees_Jobs (employees_id, jobs_id)
VALUES (1, 1),
       (2, 2),
       (3, 2),
       (4, 7),
       (5, 3),
       (6, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (7, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (8, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (9, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (10, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (11, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (12, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (13, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (14, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (15, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (16, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (17, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (18, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (19, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (20, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (21, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (22, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (23, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (24, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (25, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (26, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (27, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (28, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (29, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (30, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (31, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (32, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (33, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (34, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (35, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (36, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (37, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (38, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (39, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (40, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (41, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (42, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (43, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (44, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (45, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (46, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (47, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (48, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (49, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (50, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (51, FLOOR(RAND() * (15 - 3 + 1)) + 3),
       (52, FLOOR(RAND() * (15 - 3 + 1)) + 3);

INSERT INTO Employees_MobilePlans (employees_id, mobilePlans_id)
VALUES (1, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (2, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (3, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (4, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (5, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (6, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (7, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (8, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (9, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (10, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (21, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (22, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (23, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (24, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (25, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (26, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (27, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (28, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (29, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (30, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (31, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (32, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (33, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (34, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (35, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (36, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (37, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (38, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (39, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (40, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (41, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (42, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (43, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (44, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (45, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (46, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (47, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (48, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (49, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (50, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (51, FLOOR(RAND() * (5 - 1 + 1)) + 1),
       (52, FLOOR(RAND() * (5 - 1 + 1)) + 1);